In [1]:
# Imports with all of my tools
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import numpy as np
import cv2
from collections import Counter
from skimage.color import rgb2lab, deltaE_cie76
import os
import random
from sympy import mod_inverse
from PIL import Image as im

%matplotlib inline


def get_image(image_path):
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    print(image.shape)
    return image

In [2]:
#path = r"C:\Users\soule\OneDrive\Pictures\UI_Goku.jpg"
#path = r"C:\Users\soule\OneDrive\Pictures\Freddy.png"
path = r"C:\Users\soule\OneDrive\Pictures\addie.jpg"
l = get_image(path)
img = im.open(path)
colors = img.getpixel((0, 1))
print(colors)
rows, cols, dims = l.shape
# print(l)
data = im.fromarray(l.astype(np.uint8))
# print(l)
data.show()

(450, 600, 3)
(30, 31, 35)


In [3]:
def Generate_Point(a, b, p):
    x = 3537294  # random.randint(0, p)
    possibilites = []
    for y in range(p):
        yval = int((x ** 3) % p)
        yval = int((yval + (a * x)) % p)
        yval = int((yval + b) % p)
        # yval = ((x ** 3) + (a * x) + b) % p
        # print(yval)
        # print(x[i],y[j],y[j]**2 % p, yval)
        # print(yval)
        testy = int((y ** 2) % p)
        if testy == yval:
            return x, y


def IntegerDigits(p, b):
    arr = []
    while p >= 1:
        arr.append(p % b)
        p = p // b
        print(arr)
    A = arr[::-1]
    return len(A) - 1


def IntegerToArray(n, base):
    A = []
    while n >= 1:
        A.append(n % base)
        n = n // base
    Aflip = A[::-1]
    return Aflip


def singleLargeInteger(A, base):
    integer = 0
    power = 0
    Anew = A[::-1]
    for i in range(len(Anew)):
        integer += Anew[i] * base ** i
        # print(integer)
    return integer


def point_addition(x1, y1, x2, y2, p, a):
    z = 0
    if x1 == z and y1 == z:
        return x2, y2
    if x2 == z and y2 == z:
        return x1, y1
    if x1 == x2:
        if x1 == x2 and y1 == -y2 % p:
            return 0, 0
        else:
            den = int(mod_inverse(2 * y1, p) % p)
            m = int((3 * (x1 ** 2)) % p)
            m = int((m + a) % p)
            m = int((m * den) % p)
            m = int((((3 * (x1 ** 2)) % p + a) * (den)) % p)
            # m = (((3*(x1**2))%p + a) * (2*))
            # m = ((3*pow(x1, 2, p) + a)*pow(2*y1, p-2, p)) % p
            # print(m)
    else:
        den = int(mod_inverse(x1 - x2, p) % p)
        m = int((y1 - y2) % p)
        m = int((m * den) % p)
        # m = int(((y1 - y2)*den)%p)
        # print(m)
    x = int((m ** 2) % p)
    x = int((x - x1 - x2) % p)
    # x = int(((m**2)%p - x1 - x2) % p)
    # print(x)
    y = int((x1 - x) % p)
    y = int((y * m) % p)
    y = int((y - y1) % p)
    # y = int((m*(x1 - x)%p - y1) % p)
    # print(y)
    return int(x), int(y)


def point_subtraction(x1, y1, x2, y2, p, a):
    y2 = int(-(y2))
    y2 = int(y2 % p)
    return point_addition(x1, y1, x2, y2, p, a)


def point_multiplication(x, y, k, p, a):
    xnew, ynew = int(x), int(y)
    for i in range(k - 1):
        xnew, ynew = point_addition(x, y, xnew, ynew, p, a)
        # print(xnew,ynew)
    return int(xnew), int(ynew)

In [4]:
arr = []
for i in range(rows):
    for j in range(cols):
        for k in range(dims):
            arr.append(l[i][j][k])
print(arr[0], arr[1], arr[2])
# print(l)

29 30 34


In [5]:
1054 // 256

4

In [6]:
totalPixs = rows * cols
print(totalPixs)

totalValues = rows * cols * dims
print(totalValues)
individual_colors_arr = np.reshape(arr, (totalValues // 3, 3), order="C")

pixel_arr = []
for i in range(totalValues // 3):
    newValue = singleLargeInteger(individual_colors_arr[i], 256)
    pixel_arr.append(newValue)

groupSize = IntegerDigits(totalPixs, 256)
print(groupSize)
groupedArray = np.reshape(pixel_arr, (totalPixs // groupSize, groupSize), order="C")
groupedArray = groupedArray.astype("int64")
print(groupedArray)

270000
810000
[176]
[176, 30]
[176, 30, 4]
2
[[1908258 1974051]
 [2105637 2303016]
 [2500395 2631981]
 ...
 [5397810 5989681]
 [6449710 7436341]
 [8882504 7040555]]


In [7]:
16777215 + (16777215 ** 2)

281474959933440

In [8]:
Pm = []
for i in range(totalPixs // groupSize):
    newValue = singleLargeInteger(groupedArray[i], 16777216)
    Pm.append(newValue)
print(len(Pm))
maxValue = 0
for i in Pm:
    if i > maxValue:
        maxValue = i
print("Max: " + str(maxValue))
if len(Pm) % 2 == 1:
    Pm.append(0)
    print("activated")
print(len(Pm))
print(Pm[0], Pm[1])
# print(maxP)

135000
Max: 281474976710655
135000
32015258623779 35326729069608


In [9]:
imagePointsArray = np.reshape(Pm, (len(Pm) // 2, 2), order="C")
print(imagePointsArray)

[[ 32015258623779  35326729069608]
 [ 41949669632301  46364963318832]
 [ 47468786559534  40845845799462]
 ...
 [ 75158290779683  51943857930535]
 [ 49727638423332  90560230286641]
 [108208185243701 149023695269419]]


In [10]:
p = 18014398241046527  # 1073676287  # 1046527  # 16127
a = -5000
b = 76193

In [11]:
# armins private keys
private_A = 712
# point_A = Generate_Point(a, b, p)
point_A = [3537294, 355471301]
print(point_A)

[3537294, 355471301]


In [12]:
x1 = 3537294
y1 = 355471301
xval = (x1 ** 3 + (a * x1) + b) % p
yval = (y1 ** 2) % p
print(xval, yval)

16848117959144065 259058147306912


In [13]:
# armins public key
public_A = point_multiplication(point_A[0], point_A[1], private_A, p, a)
print(public_A)

(14793776336358049, 3737597295942823)


In [14]:
# Erins key is 92
e_key = 92

In [15]:
coordinates, variables = imagePointsArray.shape
c2 = []
print(coordinates)
r = coordinates
c1 = point_multiplication(point_A[0], point_A[1], e_key, p, a)
added_to_M = point_multiplication(public_A[0], public_A[1], e_key, p, a)
for i in range(coordinates):
    c2_operation = point_addition(
        imagePointsArray[i][0],
        imagePointsArray[i][1],
        added_to_M[0],
        added_to_M[1],
        p,
        a,
    )
    c2.append(c2_operation[0])
    c2.append(c2_operation[1])
print(len(c2))

67500
135000


In [16]:
final_encrypted_array = []
for i in range(len(c2)):
    for j in range(groupSize):
        final_encrypted_array.append(c2[i] // (256 ** j))
print(len(final_encrypted_array))

270000


In [17]:
encryption_arr = np.array(final_encrypted_array)
encryption_arr = np.reshape(encryption_arr, (rows, cols), order="C")
print(encryption_arr.shape)
# for i range(rows):
#    for j in range(cols):
#        value = encryption_arr[i][j]
# e2 = encryption_arr % 256
# print(e2)

(450, 600)


In [18]:
print(459362 % 256)

98


In [19]:
e_data = im.fromarray(encryption_arr.astype(np.uint8))
#e_data.save("addie_Encrypted.jpg")
e_data.show()

# Decryption
data = encryption_arr
x, y = data.shape
print(x, y)
print(data.shape)
# print(data)

In [20]:
arr = []
for i in range(rows):
    for j in range(cols):
        arr.append(encryption_arr[i][j])
print(len(arr))
print(arr[0], arr[1], arr[2], arr[3])
# print(arr)

270000
3033769800746954 11850663284167 1384110026469356 5406679790895


In [21]:
original_arr = []
arr = np.reshape(arr, (totalPixs // groupSize, groupSize), order="C")
for i in range(totalPixs // groupSize):
    original_arr.append(arr[i][0])
print(len(original_arr))

135000


x = x // 2

In [22]:
# newTotal = x * y
EmPointsArray = np.reshape(original_arr, (len(original_arr) // 2, 2), order="C")
print(EmPointsArray)

[[ 3033769800746954  1384110026469356]
 [ 9814385684058553  6893919098119200]
 [13940987470907310  5659402900917132]
 ...
 [13892022653093875 16287503742853119]
 [  851677443928384 17215024479198624]
 [12907152201209536 17515324058388560]]


In [23]:
coordinates, variables = EmPointsArray.shape
subtract_from_c2 = point_multiplication(c1[0], c1[1], private_A, p, a)
decrypted_array = []
print(coordinates)
r = coordinates
for i in range(coordinates):
    # C_E - (alpha * (G+B_1) + B_A)
    DP = point_subtraction(
        EmPointsArray[i][0],
        EmPointsArray[i][1],
        subtract_from_c2[0],
        subtract_from_c2[1],
        p,
        a,
    )
    decrypted_array.append(DP[0])
    decrypted_array.append(DP[1])
print(len(decrypted_array))
print(decrypted_array[0], decrypted_array[1])

67500
135000
32015258623779 35326729069608


In [24]:
plaintext_array = []
# print(plaintext_array[0])
for i in range(len(decrypted_array)):
    arr = IntegerToArray(decrypted_array[i], 16777216)
    while len(arr) > groupSize:
        arr.remove(arr[0])
    while len(arr) < groupSize:
        arr.insert(0, 0)
    for j in arr:
        plaintext_array.append(j)
print(len(plaintext_array))

270000


In [25]:
plaintext_array_color = []
for i in range(len(plaintext_array)):
    arr = IntegerToArray(plaintext_array[i], 256)
    while len(arr) > 3:
        arr.remove(arr[0])
    while len(arr) < 3:
        arr.insert(0, 0)
    for j in arr:
        plaintext_array_color.append(j)
print(len(plaintext_array_color))

810000


In [26]:
decryption_arr = np.array(plaintext_array_color, dtype=int)
decryption_arr = np.reshape(decryption_arr, (rows, cols, 3), order="C")
# decryption_arr

In [27]:
d_data = im.fromarray(decryption_arr.astype(np.uint8))
#d_data.save("addie_Decrypted.jpg")
d_data.show()