In [1]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import numpy as np
import cv2
from collections import Counter
from skimage.color import rgb2lab, deltaE_cie76
import os
import random
from sympy import mod_inverse
from PIL import Image as im

%matplotlib inline
def get_image2(image_path):
    """Get a numpy array of an image so that one can access values[x][y]."""
    image = im.open(image_path, "r")
    width, height = image.size
    pixel_values = list(image.getdata())
    if image.mode == "RGB":
        channels = 3
    elif image.mode == "L":
        channels = 1
    else:
        print("Unknown mode: %s" % image.mode)
        return None
    pixel_values = np.array(pixel_values).reshape((width, height, channels))
    return pixel_values
#mod_inverse?
def get_image(image_path):
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    print(image.shape)
    return image

In [2]:
#path = r'C:\Users\soule\OneDrive\Pictures\addie.jpg'
path = r'C:\Users\soule\OneDrive\Pictures\dbzf.jpg'
l = get_image(path)
img = im.open(path)
colors = img.getpixel((0,0))
print(colors)
rows,cols = l.shape
print(l)
data = im.fromarray(l.astype(np.uint8)) 
data.show() 

(852, 1136)
(78, 73, 95)
[[ 77  77  77 ... 121 119 118]
 [ 77  77  77 ... 121 119 118]
 [ 77  77  77 ... 121 120 119]
 ...
 [199 198 198 ... 197 197 197]
 [197 197 197 ... 196 196 196]
 [197 196 196 ... 194 194 194]]


In [3]:
new_arr = []
for i in range(rows):
    for j in range(cols):
        new_arr.append(l[i][j])

In [4]:
def IntegerDigits(p,b):
    arr = []
    while p>=1:
        arr.append(p%b)
        p = p//b
        print(arr)
    A = arr[::-1]
    return len(A)-1

def IntegerToArray(n,base):
    A = []
    while n>=1:
        A.append(n%base)
        n = n//base
    Aflip = A[::-1]
    return Aflip

def singleLargeInteger(A,base):
    integer = 0
    power = 0
    Anew = A[::-1]
    for i in range(len(Anew)):
        integer += (Anew[i] * base**i)
        #print(integer)
    return integer

def Generate_Point(a,b,p):
    x = random.randint(0,p)
    y = np.arange(0,p)
    possibilites = []
    for i in range(len(y)):
        yval = ((x**3) + (a*x) + b)%p
            #print(x[i],y[j],y[j]**2 % p, yval)
            #print(yval)
        if (((y[i])**2)%p == yval):
            possibilites.append(y[i])
    if(len(possibilites)==0):
        return Generate_Point(a,b,p)
    else:
        yindex = random.randint(0,len(possibilites)-1)
        return x, possibilites[yindex]               

In [5]:
singleLargeInteger([77,77],256)

19789

In [6]:
IntegerDigits(6277101735386680763835789423207666416083908700390324961279,65536)

[65535]
[65535, 65535]
[65535, 65535, 65535]
[65535, 65535, 65535, 65535]
[65535, 65535, 65535, 65535, 65534]
[65535, 65535, 65535, 65535, 65534, 65535]
[65535, 65535, 65535, 65535, 65534, 65535, 65535]
[65535, 65535, 65535, 65535, 65534, 65535, 65535, 65535]
[65535, 65535, 65535, 65535, 65534, 65535, 65535, 65535, 65535]
[65535, 65535, 65535, 65535, 65534, 65535, 65535, 65535, 65535, 65535]
[65535, 65535, 65535, 65535, 65534, 65535, 65535, 65535, 65535, 65535, 65535]
[65535, 65535, 65535, 65535, 65534, 65535, 65535, 65535, 65535, 65535, 65535, 65535]


11

In [7]:
p = 514229
totalPixs = rows*cols
print(totalPixs)
groupSize = IntegerDigits(p,256)
print(groupSize)
#groupedArray = np.reshape(l, (totalPixs//groupSize, groupSize), order='C')
groupedArray = np.reshape(new_arr, (totalPixs//2, groupSize), order='C')
groupedArray = groupedArray.astype('int64')
print(groupedArray)

967872
[181]
[181, 216]
[181, 216, 7]
2
[[ 77  77]
 [ 77  77]
 [ 77  77]
 ...
 [194 194]
 [194 194]
 [194 194]]


In [8]:
groupedArray[0]

array([77, 77], dtype=int64)

Pm = []
for i in range(totalPixs//groupSize):
    newValue = singleLargeInteger(groupedArray[i],256)
    Pm.append(newValue)
print(len(Pm))
if len(Pm)%2 == 1:
    Pm.append(0)
    print('activated')
print(len(Pm))
print(Pm[0],Pm[1])
#print(maxP)

In [9]:
imagePointsArray = groupedArray
#imagePointsArray = np.reshape(Pm, (len(Pm)//2, 2), order='C')
imagePointsArray = imagePointsArray.astype('int64')
print(imagePointsArray)

[[ 77  77]
 [ 77  77]
 [ 77  77]
 ...
 [194 194]
 [194 194]
 [194 194]]


In [10]:
#3803
p = 514229
a = -500
b = 761


In [11]:
#G = random point
Gx, Gy = Generate_Point(a,b,p)
print(Gx,Gy)

28886 201831


In [12]:
private_a = 741
private_Ax, private_Ay = Generate_Point(a,b,p)
print(private_Ax, private_Ay)

208351 119337


In [13]:
private_b = 9812
private_Bx, private_By = Generate_Point(a,b,p)
print(private_Bx, private_By)

377413 48588


In [14]:
def point_addition(x1,y1,x2,y2,p,a):
    z = 0
    if (x1 == z and y1 == z):
        return x2, y2
    if (x2 == z and y2 == z):
        return x1,y1
    if x1 == x2:
        if (x1 == x2 and y1 == -y2%p):
            return 0, 0
        else:
            den = int(mod_inverse(2*y1,p)%p)
            m = int((3*(x1**2))%p)
            m = int((m+a)%p)
            m = int((m*den)%p)
            m = int((((3*(x1**2))%p + a)*(den))%p)
            #m = (((3*(x1**2))%p + a) * (2*))
            #m = ((3*pow(x1, 2, p) + a)*pow(2*y1, p-2, p)) % p
            #print(m)
    else:
        den = int(mod_inverse(x1-x2,p)%p)
        m = int((y1-y2)%p)
        m = int((m*den)%p)
        #m = int(((y1 - y2)*den)%p)
        #print(m)
    x = int((m**2)%p)
    x = int((x-x1-x2)%p)
    #x = int(((m**2)%p - x1 - x2) % p)
    #print(x)
    y = int((x1-x)%p)
    y = int((y*m)%p)
    y = int((y-y1)%p)
    #y = int((m*(x1 - x)%p - y1) % p)
    #print(y)
    return int(x), int(y)

def point_subtraction(x1,y1,x2,y2,p,a):
    y2 = int(-(y2))
    y2 = int(y2%p)
    return point_addition(x1,y1,x2,y2,p,a)

def point_multiplication(x,y,k,p,a):
    xnew,ynew = int(x),int(y)
    for i in range(k-1):
        xnew,ynew = point_addition(x,y,xnew,ynew,p,a)
        #print(xnew,ynew)
    return int(xnew),int(ynew)

In [15]:
x,y = point_addition(9,4,10,20,37,2)
print(x,y)
point_multiplication(x,y,5,37,2)

15 11


(1, 7)

In [16]:
G_plus_Ax, G_plus_Ay = point_addition(Gx,Gy,private_Ax,private_Ay,p,a)

In [17]:
A1x, A1y = point_multiplication(G_plus_Ax, G_plus_Ay, private_a, p, a)

In [18]:
A2x, A2y = point_multiplication(private_Ax, private_Ay, private_a, p, a)

In [19]:
2**32

4294967296

In [20]:
G_plus_Bx, G_plus_By = point_addition(Gx, Gy, private_Bx, private_By, p, a)

In [21]:
B1x, B1y = point_multiplication(G_plus_Bx, G_plus_By, private_b, p, a)

In [22]:
B2x, B2y = point_multiplication(private_Bx, private_By, private_b, p, a)

In [23]:
A_Bx, A_By = point_multiplication(B2x, B2y, private_a, p, a)

In [24]:
B_Ax, B_Ay = point_multiplication(A2x, A2y, private_b, p, a)

In [25]:
b_plus_one_A1 = point_multiplication(A1x,A1y,(private_b+1),p,a)

b_plus_one_A1_minus_A2 = point_subtraction(b_plus_one_A1[0],b_plus_one_A1[1],A2x,A2y,p,a)

added_to_M = point_addition(b_plus_one_A1_minus_A2[0],b_plus_one_A1_minus_A2[1],A_Bx,A_By,p,a)

In [26]:
coordinates, variables = imagePointsArray.shape
print(imagePointsArray.shape)
encrypted_array = []
print(coordinates)
r=coordinates
for i in range(coordinates):
    EP = point_addition(imagePointsArray[i][0],imagePointsArray[i][1],added_to_M[0],added_to_M[1],p,a)
    encrypted_array.append(EP[0])
    encrypted_array.append(EP[1])
print(len(encrypted_array))
print(encrypted_array[0])

(483936, 2)
483936
967872
282286


final_encrypted_array = []
for i in range(len(encrypted_array)):
    value = encrypted_array[i]%256
    divisor = encrypted_array[i]//256
    final_encrypted_array.append(value)
    final_encrypted_array.append(divisor)
print(len(final_encrypted_array))

#967872
cipher_array = []
extra_array = []
for i in range(len(encrypted_array)):
    #encrypted_array[i] = encrypted_array[i]%256
    arr = IntegerToArray(encrypted_array[i],256)
    #while len(arr)>2:
        #arr.remove(arr[0])
    while len(arr)<2:
        arr.insert(0,0)
    for j in arr:
        cipher_array.append(j)
print(len(cipher_array))

#967872
cipher_array = []
arr = []
for i in range(len(encrypted_array)):
    for j in range(groupSize):
        cipher_array.append(encrypted_array[i]//256**j)
    #encrypted_array[i] = encrypted_array[i]%256
    #arr = IntegerToArray(encrypted_array[i],256)
    #while len(arr)>2:
        #arr.remove(arr[0])
    #while len(arr)<2:
        a#rr.insert(0,0)
    #for j in arr:
        #cipher_array.append(j)
print(len(cipher_array))

In [27]:
encryption_arr = np.array(encrypted_array, dtype=int)
#encryption_arr = np.array(cipher_array, dtype=int)
encryption_arr = np.reshape(encryption_arr, (rows, cols), order='C')
encryption_arr

array([[282286, 364036, 282286, ..., 420483, 328285, 416152],
       [282286, 364036, 282286, ..., 420483, 328285, 416152],
       [282286, 364036, 282286, ..., 451444, 311964, 426945],
       ...,
       [266243, 268054, 292020, ..., 478106, 428595, 478106],
       [428595, 478106, 428595, ..., 258509,  20798, 258509],
       [    45,  55399,  20798, ..., 119190, 162499, 119190]])

In [28]:
256**2

65536

In [29]:
e_data = im.fromarray(encryption_arr.astype(np.uint8)) 
e_data.show() 

In [30]:
#Decryption
data = encryption_arr
rows,cols = data.shape
print(data.shape)
print(data)

(852, 1136)
[[282286 364036 282286 ... 420483 328285 416152]
 [282286 364036 282286 ... 420483 328285 416152]
 [282286 364036 282286 ... 451444 311964 426945]
 ...
 [266243 268054 292020 ... 478106 428595 478106]
 [428595 478106 428595 ... 258509  20798 258509]
 [    45  55399  20798 ... 119190 162499 119190]]


totalPixs = rows*cols
print(totalPixs)
#groupSize = IntegerDigits(totalPixs,256)
groupedArray = np.reshape(data, (totalPixs//2, 2), order='C')
print(groupedArray)

Em = []
for i in range(totalPixs//groupSize):
    Em.append(groupedArray[i][0])
print(len(Em))
if len(Em)%2 == 1:
    Em.append(0)
print(Em[0],Em[1])
if (encrypted_array==Em):
    print('true')

In [31]:
#applied_data = np.reshape(data, (totalPixs//2, 2), order='C')
#print(apply_divisor)
#applied_data = []
#for i in range(totalPixs//2):
    #newValue = apply_divisor[i][1]*256 + apply_divisor[i][0]
    #applied_data.append(newValue)
#print((applied_data))

In [32]:
#rows = rows//2
#newTotal = rows*cols
EmPointsArray = np.reshape(encryption_arr, (totalPixs//2, 2), order='C')
print((EmPointsArray))

[[282286 364036]
 [282286 364036]
 [282286 364036]
 ...
 [162499 119190]
 [162499 119190]
 [162499 119190]]


In [33]:
G_plus_B1 = point_addition(Gx,Gy,B1x,B1y,p,a)
private_a_G_plus_B1 = point_multiplication(G_plus_B1[0],G_plus_B1[1],private_a,p,a)
private_a_G_plus_B1_plus_BA = point_addition(private_a_G_plus_B1[0],private_a_G_plus_B1[1],B_Ax,B_Ay,p,a)

In [34]:
coordinates, variables = EmPointsArray.shape
decrypted_array = []
print(coordinates)
r=coordinates
for i in range(coordinates):
    DP = point_subtraction(EmPointsArray[i][0],EmPointsArray[i][1],private_a_G_plus_B1_plus_BA[0],private_a_G_plus_B1_plus_BA[1],p,a)
    decrypted_array.append(DP[0])
    decrypted_array.append(DP[1])
print(len(decrypted_array))
print(decrypted_array[0],decrypted_array[1])

483936
967872
350906 162843


In [35]:
IntegerToArray(201762,256)

[3, 20, 34]

plaintext_array = []
#print(plaintext_array[0])
for i in range(len(decrypted_array)):
    arr = IntegerToArray(decrypted_array[i],256)
    #while len(arr)>groupSize:
        #arr.remove(arr[0])
    #while len(arr)<groupSize:
        #arr.insert(0,0)
    for j in arr:
        plaintext_array.append(j)
print(len(plaintext_array))

In [36]:
decryption_arr = np.array(decrypted_array, dtype=int)
#decryption_arr = np.array(plaintext_array, dtype=int)
decryption_arr = np.reshape(decryption_arr, (rows, cols), order='C')
decryption_arr

array([[350906, 162843, 350906, ..., 163529,  22653, 417796],
       [350906, 162843, 350906, ..., 163529,  22653, 417796],
       [350906, 162843, 350906, ...,  40473, 420567,    580],
       ...,
       [226551, 148061, 177916, ..., 370110, 401969, 370110],
       [401969, 370110, 401969, ..., 319568, 386679, 319568],
       [ 64719, 445679, 386679, ..., 132785, 504454, 132785]])

In [37]:
d_data = im.fromarray(decryption_arr.astype(np.uint8)) 
d_data.show() 